# Generated by Django 6.0.6 on 2026-06-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='compay',
            new_name='company',
        ),
    ]
