# Generated by Django 6.0.1 on 2026-06-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='content',
            field=models.TextField(default='No content provided'),
        ),
    ]
