# Generated by Django 6.0.6 on 2026-06-19 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_thread_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='Category',
            new_name='category',
        ),
        migrations.CreateModel(
            name='Reply_to_Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repliesto', to='forum.reply')),
            ],
        ),
    ]
