# Generated by Django 6.0.6 on 2026-06-19 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_rename_category_thread_category_reply_to_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_replies', to='forum.reply')),
            ],
        ),
        migrations.DeleteModel(
            name='Reply_to_Reply',
        ),
    ]
