# Generated by Django 6.0.6 on 2026-07-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_customuser_about_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobileno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
