# Generated by Django 6.0.6 on 2026-07-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_customuser_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
