# Generated by Django 6.0.6 on 2026-07-26 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_customuser_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Topic')),
                ('description', models.TextField(verbose_name='Summary / Brief')),
                ('event_type', models.CharField(choices=[('WEBINAR', 'Webinar (Online)'), ('EVENT', 'Event (In-Person)')], default='WEBINAR', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='City or Full Address (For Events)', max_length=255, null=True)),
                ('meeting_link', models.URLField(blank=True, help_text='Zoom, Meet, or Teams link (For Webinars)', null=True)),
                ('participation_fee', models.CharField(blank=True, help_text="e.g., 'Free', '$50', '₹1500'", max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Must be checked by Admin for the event to show publicly.')),
                ('max_attendees', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='forum.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
