# Generated by Django 6.0.6 on 2026-08-02 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
