# Generated by Django 6.0.6 on 2026-08-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_privatenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='badge_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
